enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
enabled = true
exclusive-patches = true
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
cli-source = "inotia00/revanced-cli"
patches-source = "anddea/revanced-patches"
integrations-source = "anddea/revanced-integrations"
rv-brand = "ReX"
arch = "arm64-v8a"
build-mode = "both"
included-patches = "'Alternative thumbnails' 'Ambient mode control' 'Change Shorts repeat state' 'Change player flyout menu toggles' 'Change start page' 'Custom double tap length' 'Custom package name' 'Description components' 'Disable QUIC protocol' 'Disable auto audio tracks' 'Disable auto captions' 'Disable haptic feedback' 'Disable resuming Shorts on startup' 'Disable splash animation' 'Enable OPUS codec' 'Enable debug logging' 'Enable external browser' 'Enable gradient loading screen' 'Enable open links directly' 'Force custom branding wordmark header' 'Force hide player buttons background' 'Fullscreen components' 'Hide Shorts dimming' 'Hide action buttons' 'Hide ads' 'Hide animated button background' 'Hide comments components' 'Hide double tap overlay filter' 'Hide double tap to like animations' 'Hide feed components' 'Hide layout components' 'Hide feed flyout menu' 'Hide player buttons' 'Hide player flyout menu' 'Layout switch' 'MaterialYou' 'Miniplayer' 'Navigation bar components' 'Overlay buttons' 'Player components' 'Remove background playback restrictions' 'Remove viewer discretion dialog' 'Return YouTube Dislike' 'Sanitize sharing links' 'Seekbar components' 'Settings for YouTube' 'Shorts components' 'Shorts overlay buttons' 'SponsorBlock' 'Spoof app version' 'Spoof client' 'Swipe controls' 'Theme' 'Toolbar components' 'Translations' 'Video playback' 'Visual preferences icons'"
excluded-patches = "'Force snackbar theme' 'Custom branding name YouTube' 'Custom branding icon YouTube'"
patches-version = "v2.226.0-dev.19"
integrations-version = "v0.153.0-dev.10"

[Music]
enabled = true
exclusive-patches = true
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
cli-source = "inotia00/revanced-cli"
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
rv-brand = "Music"
arch = "arm64-v8a"
build-mode = "both"
included-patches = "'Custom package name' 'Amoled' 'Bitrate default value' 'Certificate spoof' 'Change start page' 'Disable auto captions' 'Disable dislike redirection' 'Enable Cairo splash animation' 'Enable OPUS codec' 'Enable debug logging' 'Enable landscape mode' 'Flyout menu components' 'GmsCore support' 'Hide account components' 'Hide action bar components' 'Hide ads' 'Hide double tap overlay filter' 'Hide layout components' 'Hide overlay filter' 'Hide player overlay filter' 'Navigation bar components' 'Player components' 'Remove background playback restrictions' 'Remove viewer discretion dialog' 'Restore old style library shelf' 'Return YouTube Dislike' 'Sanitize sharing links' 'Settings for YouTube Music' 'SponsorBlock' 'Spoof app version' 'Translations' 'Video playback' 'Visual preferences icons'"
excluded-patches = "'Custom branding icon YouTube Music' 'Custom branding name YouTube Music'"


